language: r
sudo: required
cache: packages

r:
# - oldrel
 - release
 - devel

addons:
  apt:
    packages:
      - libhunspell-dev

before_install:
  - sudo apt-get install libgmp3-dev
  - sudo apt-get install libmpfr-dev

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
